// Generated by Assets/Hananoki/ProjectExtension/AutoBackup/Localize/en-US.csv

namespace HananokiEditor.AutoBackup {
	public static class L {
		public static string Tr( int n ) {
			try {
				return EditorLocalize.GetPakage( Package.name ).m_Strings[ n ];
			}
			catch( System.Exception ) {
			}
			return string.Empty;
		}
	}
	public static class S {
		public static string _Backuppackage => L.Tr( 0 );
		public static string _PackageName => L.Tr( 1 );
		public static string _Stoppedworking => L.Tr( 2 );
		public static string _DisablethebackuppackagefromPackageManager => L.Tr( 3 );
		public static string _Backupfunctionisworking => L.Tr( 4 );
		public static string _Backupfunctionhasstoppedworking => L.Tr( 5 );
		public static string _Backupinterval_minutes_ => L.Tr( 6 );
		public static string _Save__Backupscenesatstartofplaymode => L.Tr( 7 );
		public static string _CallSaveAssetswhenbackingup => L.Tr( 8 );
		public static string _Deleteoldfileswhenthespecifiednumberoffilesisexceeded => L.Tr( 9 );
		public static string _Backupyourscenenow => L.Tr( 10 );
		public static string _Cleanupbackup => L.Tr( 11 );
		public static string _Usedforthedisplaynameofthepackageandthenameoftheoutputfolder => L.Tr( 12 );
		public static string _Nopackagenameentered => L.Tr( 13 );
		public static string _Doyouwanttooverwritetheoriginalfilewiththisbackup_ => L.Tr( 14 );
		public static string _Itwillstopworkingbecausethebackuppackagedisappearedduringoperation => L.Tr( 15 );
	}

#if UNITY_EDITOR
  public class LocalizeEvent {
    [HananokiEditorLocalizeRegister]
    public static void Changed() {
			EditorLocalize.Load( Package.name, "a49eb1fe2f4472044a370e99f418e861" );
		}
	}
#endif
}
